name: Auto Update Superenalotto

on:
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   # QUESTA PARTE È FONDAMENTALE PER SCRIVERE SUL CSV
   permissions:
     contents: write

   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
         token: ${{ secrets.GITHUB_TOKEN }}

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.x'

     - name: Run update script
       run: python update_data.py

     - name: Commit and push changes
       run: |
         git config --global user.name "GitHub Action"
         git config --global user.email "action@github.com"
         git add storico_completo.csv
         git commit -m "Aggiunto 05-mag" || exit 0
         git push
