name: Auto Update Superenalotto

on:
 workflow_dispatch: # Questo ti permette di premere "Run workflow" a mano

jobs:
 build:
   runs-on: ubuntu-latest
   # Questa sezione dà il permesso fisico di SCRIVERE sul tuo repository
   permissions:
     contents: write

   steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.x'

     - name: Run update script
       run: python update_data.py

     - name: Commit and push changes
       run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         git add storico_completo.csv
         # Se non ci sono modifiche, non dà errore (|| echo...)
         git commit -m "Aggiornamento estrazione 05-mag" || echo "Nessuna modifica"
         git push
